#################################################################################
# This pipeline.ini file lists some configuration options that you might 	#
# want a user to set automatically.						#
# Add pipeline specific options into separate sections				#
#################################################################################

## general options

# Project name
projectname: ATACseq Pipeline

# The short X.Y version.
version: 0.1

########################################################
# the genome to use (UCSC convention)
genome: mm10

################################################################
# Location of narrowpeak peak file for annotation 
peak_file_gtf: /ifs/projects/proj078/1_atac_seq/6_differential_analysis/1_single/merged_downsampled_pooled.macs2_peaks.narrowPeak


################################################################
# Location of gtf peak file for rsubread
peak_file: /ifs/projects/proj078/1_atac_seq/6_differential_analysis/1_single/merged_downsampled_pooled.macs2_peaks.gff

################################################################
#Location of sample sheet for deseq
sample_sheet: /ifs/projects/proj078/1_atac_seq/SteveW_Rproject/sample_sheet.csv

################################################################
#Gene for for deseq
gene: nothing

################################################################
